language: node_js
node_js:
- node
cache:
- npm
- yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: oss@mathieutu.dev
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: mathieutu/vue-cli-plugin-express
